### ISSUE TITLE
Can I use these icons with FluentAvalonia

### ISSUE THREAD

**Issue by masterWeber** [davidxuang/FluentIcons#1]
Can I use these icons with FluentAvalonia, for example for [NavigationViewItem](https://github.com/amwx/FluentAvalonia/blob/master/FluentAvalonia/UI/Controls/NavigationView/Items/NavigationViewItem.cs)?
https://github.com/amwx/FluentAvalonia

**Comment by davidxuang** [comment]
No, as for `FluentIcons.Avalonia`. As a workaround, I’ve just released a new package `FluentIcons.FluentAvalonia` where `SymbolIcon` is built upon `FontIcon` from `FluentAvalonia`. It should work with all `FluentAvalonia` v1.3.0+ controls since the `FontIcon` APIs haven’t change since then, but I haven’t tested it for v2 yet. So please leave some feedback whether it works on v2 or not.

**Comment by masterWeber** [comment]
> Please note that for now, only `preview` versions works for `FluentAvalonia` v2.

Not buildable for v2, because avalonia v11 is used there.

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Visuals, Version=0.10.13.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The system cannot find the file specified.`

**Comment by davidxuang** [comment]
Use the version with `preview` suffix. Latest is `1.1.182-preview`.

![图片](https://user-images.githubusercontent.com/24728204/191019312-6a8fcbd9-ed98-4c36-86ac-3e0e63ded402.png)

**Comment by NPadrutt** [comment]
I just stumbled over this question. I'm currently try to achieve this aswell. I declared it like this and it starts, but the icon isn't shown. It's just empty. Any idea what I'm doing wrong? 

```
    <ui:NavigationView x:Name="NavigationView"
                       ItemInvoked="NavigationView_OnItemInvoked"
                       IsBackButtonVisible="True"
                       IsBackEnabled="{Binding CanGoBack, Mode=OneWay}"
                       BackRequested="NavigationView_OnBackRequested">
        <ui:NavigationView.MenuItems>
            <ui:NavigationViewItem Content="{x:Static lang:Translations.DashboardMenuItem}">
                <ui:NavigationViewItem.IconSource>
                    <ic:SymbolIconSource Symbol="Home" />
                </ui:NavigationViewItem.IconSource>
            </ui:NavigationViewItem>
            <ui:NavigationViewItem Content="{x:Static lang:Translations.StatisticsMenuItem}">
                <ui:NavigationViewItem.IconSource>
                    <ic:SymbolIconSource Symbol="ChartMultiple" />
                </ui:NavigationViewItem.IconSource>
            </ui:NavigationViewItem>
        </ui:NavigationView.MenuItems>

```

![image](https://github.com/davidxuang/FluentIcons/assets/1764367/a95ebf70-ac0e-4aa5-87d3-e72781d139ac)

**Comment by Leon99** [comment]
@NPadrutt +1.
The same code using FAvalonia's SymbolIconSource works.
