### ISSUE TITLE
Get IImage instead of control?

### ISSUE THREAD

**Issue by StefanKoell** [davidxuang/FluentIcons#13]
I was wondering if there's a way to get the IImage of the symbol instead of using it in a control/markup extension? A use case for the IImage would be to use symbols in view models to bind to MVVM driven menus/toolbar items where only IImage based properties for bindings are available.

**Comment by davidxuang** [comment]
It should be easy to get a raster image on WPF, but for vector image I only know that SkiaSharp (which Avalonia depends on) can do it.

**Comment by StefanKoell** [comment]
Thanks for the reply. In my case it would be the vector image for Avalonia.

**Comment by davidxuang** [comment]
I've made some test. One major problem is that an `IImage` object cannot invoke `InvalidateVisual()` to notify its parent that its properties and appearance have been changed. There may be some solutions:
* Make the implementation immutable. In this approach, the image cannot change automatically upon events like app theme changes.
* Provide an event to notity that the visual has been changed; developers should handle the event on there own (possibly call `InvalidateVisual()` upon notified). The cons could be that this approach is not XAML-friendly.

What do you think?

**Comment by StefanKoell** [comment]
Thanks for looking into it. In my particular case, it wouldn't be an issue because the `IImage` will be used in a control which would handle theme changes automatically (`DynamicImage` from [Acripro](https://www.actiprosoftware.com/docs/controls/avalonia/shared/controls/dynamic-image)). We are currently discussing possible solutions. They use `IImage` in a view model and bind that to a button (which hosts this `DynamicImage`). In general, I'm not very happy with that approach because it means my ViewModel needs to know a lot about the View (like dimensions or maybe theme variant). The preferred solution would be `IDataTemplate` support which allows me to put whatever control in the `ContentPresenter` - including `SymbolIcon`. 

I was just curious on how to get the actual IImage from the symbol and maybe this can help in other scenarios.

**Comment by davidxuang** [comment]
The ViewModel does not need to know a lot about the view. All you need is something like `image.VisualChanged += () => view.InvalidateVisual()`. And in most senarios (metrics/theme changes) this should be unnecessary because the view will invalidate the render cache anyway. This should only be a problem when you bind some property (probably `Symbol`) to a data model which will update in background with no user interreaction with the view.

**Comment by davidxuang** [comment]
I've pushed the implementation (https://github.com/davidxuang/FluentIcons/commit/80bacfe3bcf45e5134b14900ac73cdb7ef65ea53) for reference.

**Comment by StefanKoell** [comment]
This is awesome, thank you. Will definitely check it out!
