### ISSUE TITLE
Icon Size based on Container Size

### ISSUE THREAD

**Issue by StefanKoell** [davidxuang/FluentIcons#16]
Quick question - and maybe a feature request if it's feasible:

can the fluent icon size be specified using Width and Height instead of FontSize? The reason I ask is that I want to mix/match fluent icons with custom icons and it's quite hard to align the sizes all the time.

Thanks,
Stefan

**Comment by davidxuang** [comment]
Hmmm, I don't quite understand the situation. I'd suppose that you can specity width and height of an icon. Are you suggesting something like [Strech](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image.stretch?view=winrt-26100) property? In that case, maybe wrapping the icon with [Viewbox](https://docs.avaloniaui.net/docs/reference/controls/viewbox)?

**Comment by davidxuang** [comment]
Oh, `FontSize` is not `IconSize`. In other words, this project only uses `Size20` variant from upstream because it is the most complete one, otherwise we will suffer from either inconsistancy between icons or [tofus](https://fonts.google.com/knowledge/glossary/tofu).

Introducing a `FluentIcon` with all size variants and `IconSize=Auto` is a possible but massive project if we want to keep the `UseSegoeMetrics` feature orthogonal to this one.

**Comment by davidxuang** [comment]
> Oh, `FontSize` is not `IconSize`. In other words, this project only uses `Size20` variant from upstream because it is the most complete one, otherwise we will suffer from either inconsistancy between icons or [tofus](https://fonts.google.com/knowledge/glossary/tofu).
> 
> Introducing a `FluentIcon` with all size variants and `IconSize=Auto` is a possible but massive project if we want to keep the `UseSegoeMetrics` feature orthogonal to this one.

BTW the upstream also distribute `Size20` as the [resizable](https://github.com/microsoft/fluentui-system-icons/blob/main/fonts/FluentSystemIcons-Resizable.ttf) variant. Also introduing all size variants will also increase the package size significantly. Do your use case has a strong demand of dynamic icon size?

**Comment by StefanKoell** [comment]
That makes sense now. In my case I deal with 2 different variants (16x16 and 24x24)

would have been a nice feature to just set width and height and the FontSize is set automatically.

what are the appropriate font sizes for my two variants?

**Comment by StefanKoell** [comment]
I ended up with putting the SymbolIcon in a Viewbox (with Stretch) and set the FontSize to 20. Applying a small margin on that viewbox allows me to fine tune my template to get pretty close to the appearance of my other icons which are not font based. I'm quite happy with the result and I hope I did it right ;)

In any case, thanks for your valuable input and for the explanation here.

cheers!
