### ISSUE TITLE
UWP .NET 9 preview support

### ISSUE THREAD

**Issue by FireCubeStudios** [davidxuang/FluentIcons#18]
UWP now has .NET 9 support. It would be good for this library to support it
https://devblogs.microsoft.com/ifdef-windows/preview-uwp-support-for-dotnet-9-native-aot/

**Comment by davidxuang** [comment]
I would suppose the support has been shipped: https://github.com/davidxuang/FluentIcons/blob/9e1e8096c85b34fe0505f4461c3de1c2a2bb85b1/FluentIcons.Uwp/FluentIcons.Uwp.csproj#L4

Is there an extra compatibility issue?

**Comment by FireCubeStudios** [comment]
nuget issue on my end, confirmed it worked in a new blank app
